INCLUDE "game/src/common/constants.asm"
INCLUDE "game/src/common/macros.asm"

INCLUDE "game/src/core/main.asm"
INCLUDE "game/src/core/vblank_irq.asm"
INCLUDE "game/src/core/free.asm"
INCLUDE "game/src/core/rst.asm"
INCLUDE "game/src/core/hardware.asm"
INCLUDE "game/src/core/wrappers.asm"
INCLUDE "game/src/core/robattle_statemachine.asm"
INCLUDE "game/src/core/state_indexes.asm"
INCLUDE "game/src/core/sram.asm"
INCLUDE "game/src/core/jump_table.asm"