import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), 'common'))
from common import utils

table = utils.read_table("scripts/res/tilemaps.tbl")
with open("game/tilemaps/tilemap_files.asm", "w") as tf:
    tf.write("; auto-generated by {}\n".format(sys.argv[0]))
    tilemap_files = []
    # Pointer table
    for i in table:
        tf.write("dw {} ; Tilemap 0x{:02X}\n".format(table[i], i))
        if table[i] not in tilemap_files:
            tilemap_files.append(table[i])
    tf.write("\n")
    for file in tilemap_files:
        tf.write('{0}:\n  INCBIN "game/tilemaps/{0}.tmap"\n'.format(file))