# Simply execute 'make' to verify things still build

name: Build All

on:
  push:
    branches:
      - master
      - 'tr_*'

  # Allows running manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/medabots/medarot1:master

    steps:
      - name: List versions
        run: |
          git --version
          python3 --version
          rgbasm --version
          rgblink --version
          rgbgfx --version

      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          path: 'medarot1'

      - name: Checkout baserom repository
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.BASEROM1_REPOSITORY }}
          ssh-key: ${{ secrets.BASEROM1_KEY }}
          path: 'baserom'

      - name: Copy baserom into main repository
        run: |
          cp $GITHUB_WORKSPACE/baserom/*.gbc $GITHUB_WORKSPACE/medarot1

      - name: Make dump
        working-directory: 'medarot1'
        run: |
          make -j dump

      - name: Make all
        working-directory: 'medarot1'
        run: |
          make -j all

      - name: Verify there are no uncommitted changes
        working-directory: 'medarot1'
        run: |
          [ -z "$(git status --porcelain)" ] && exit 0 || exit 1